---
- hosts: 127.0.0.1
  become: true
  vars:
     contents: "{{ lookup('file', 'config.xml') }}"

  pre_tasks:

    - name: add repo for java 8
      apt_repository: repo='ppa:webupd8team/java' state=present

    - name: set licence selected
      shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
      sudo: yes

    - name: set licence seen
      shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
      sudo: yes

    - name: install java 8
      apt: name=oracle-java8-installer state=latest update-cache=yes force=yes

  tasks:
    - name: Install Git
      apt: pkg=git state=installed update_cache=true

    - name: Check if Appfolder exists
      command: ls
      register: list

    - name: Clone if doesn't exist
      command: git clone https://github.com/manojkumarg16/Demo.git
      when: "list.stdout.find('Demo') == -1"

    - name: Clone config.xml
      command: git clone https://github.com/manojkumarg16/DemoTesting.git
      when: "list.stdout.find('DemoTesting') == -1"


    - name: Install Maven
      apt: pkg=maven state=installed update_cache=true

    - name: Jenkis
      get_url:
        url: "http://localhost:8080/jnlpJars/jenkins-cli.jar"
        dest: /vagrant/assignments/DemoTesting

    - name: create jenkins jobs with xml files
      shell: "java -jar jenkins-cli.jar -s http://localhost:8080 create-job AnsibleDemo < DemoTesting/config.xml --username admin --password jenkinspwd16@@"
      
    - name: Build Jenkins job
      shell: "java -jar jenkins-cli.jar -s http://localhost:8080 build AnsibleDemo --username admin --password jenkinspwd16@@"